# Generated by Django 4.1.5 on 2023-04-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_one', models.CharField(max_length=50)),
                ('field_two', models.TextField()),
            ],
        ),
    ]
