# Generated by Django 4.1.5 on 2023-04-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(default='password', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='password', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
